import { ArrowRight, BarChart3, CalendarDays, Check, ChevronRight, CircleDot, Clock3, Database, Filter, FlaskConical, Gauge, LineChart, LockKeyhole, Search, ShieldCheck, SlidersHorizontal, Sparkles, Target, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import type { Candidate } from "@stock-autotrader/contracts";
import { useData } from "./lib/data-context";
import { Badge, MetricCard, PublicFooter, Rationale, SectionHeading, SignalBadge } from "./components";
import { formatDate, formatMoney } from "./lib/format";

const features = [
  [Search, "Market-wide scanning", "A rules-based universe removes illiquid securities before strategies begin."],
  [Target, "Systematic strategies", "Versioned strategy logic evaluates every eligible stock in the same way."],
  [Zap, "Earnings & events", "Event timing and price reactions are checked before a setup can pass."],
  [ShieldCheck, "Risk management", "Position size and portfolio limits remain deterministic and outside AI."],
  [Database, "Transparent methodology", "Every decision stores structured pass and rejection reasons."],
  [LineChart, "Shadow performance", "Signals are tested with simulated capital before any future broker link."]
] as const;

function LandingPreview() {
  const demoData = useData();
  const { scan, portfolio } = demoData;
  return <div className="hero-preview"><div className="preview-top"><div><span className="preview-dot" /> Engine online</div><Badge tone="demo">Demo Data</Badge></div><div className="preview-metrics"><div><span>Stocks scanned</span><strong>{scan.universe.toLocaleString()}</strong></div><div><span>Setups today</span><strong>{scan.candidates}</strong></div><div><span>Strategies</span><strong>{demoData.strategies.length}</strong></div><div><span>Shadow portfolio</span><strong>{formatMoney(portfolio.equity)}</strong><small>+{portfolio.returnPct}%</small></div></div><div className="preview-table"><div className="preview-row preview-header"><span>Symbol</span><span>Quant score</span><span>Strategy</span><span>Model signal</span></div>{demoData.candidates.slice(0, 3).map((c) => <div className="preview-row" key={c.symbol}><span><strong>{c.symbol}</strong><small>{c.company}</small></span><span><strong>{c.quantScore}</strong>/100</span><span>{c.strategy}</span><span><SignalBadge status={c.status} /></span></div>)}</div></div>;
}

export function LandingPage() {
  const demoData = useData();
  return <div className="landing">
    <header className="landing-nav"><Link to="/" className="brand"><span className="brand-mark"><BarChart3 size={19} /></span><span>Stock Autotrader<small>Systematic Research</small></span></Link><nav><a href="#overview">Overview</a><a href="#strategies">Strategies</a><a href="#analysis">Analysis</a><a href="#research">Research</a><a href="#about">About</a></nav><Link className="button button-small" to="/dashboard">View Live Dashboard</Link></header>
    <main>
      <section className="hero" id="overview"><div className="hero-copy"><Badge tone="positive"><CircleDot size={12} /> US market research engine</Badge><h1>Data. Analysis.<br /><em>Opportunity.</em></h1><p>Systematic stock research scanning the US market for high-quality swing trading setups.</p><div className="hero-actions"><Link className="button" to="/dashboard">View Live Dashboard <ArrowRight size={17} /></Link><a className="button button-secondary" href="#method">How It Works</a></div><div className="trust-row"><span><Check /> Read-only</span><span><Check /> Auditable decisions</span><span><Check /> Simulated capital</span></div></div><LandingPreview /></section>
      <section className="section" id="method"><SectionHeading eyebrow="A disciplined process" title="From the whole market to a clear decision" text="The engine narrows the universe before any event or AI assessment. Hard risk rules always stay deterministic." /><div className="process"><div><span>01</span><strong>Filter</strong><p>Liquidity, price and market-cap rules build the eligible universe.</p></div><ChevronRight /><div><span>02</span><strong>Measure</strong><p>Trend, momentum, relative strength, volume and volatility.</p></div><ChevronRight /><div><span>03</span><strong>Decide</strong><p>Versioned strategies produce an auditable quant signal.</p></div><ChevronRight /><div><span>04</span><strong>Observe</strong><p>Qualified signals enter a simulated shadow portfolio.</p></div></div></section>
      <section className="section section-tinted" id="analysis"><SectionHeading eyebrow="Built for evidence" title="One public view. No trading controls." text="The website explains what the engine observed without exposing private infrastructure or model chain-of-thought." /><div className="feature-grid">{features.map(([Icon, title, text]) => <article className="feature-card" key={title}><span className="icon-box"><Icon size={21} /></span><h3>{title}</h3><p>{text}</p><Link to="/methodology">Learn more <ArrowRight size={14} /></Link></article>)}</div></section>
      <section className="section split-section" id="strategies"><div><SectionHeading eyebrow="Versioned strategies" title="Compare ideas without mixing evidence" text="Each strategy publishes its rules, lifecycle stage and results independently. New strategies appear from metadata, not hand-built pages." /><Link className="text-link" to="/strategies">Explore strategies <ArrowRight size={16} /></Link></div><div className="strategy-stack">{demoData.strategies.map((s, index) => <article key={s.id}><div><Badge tone={s.state === "Shadow" ? "positive" : "neutral"}>{s.state}</Badge><span>v{s.version}</span></div><h3>{s.name} V1</h3><p>{s.description}</p><div><span>{s.universe}</span><span>{s.holdingPeriod}</span><strong>{index + 1} setup{index ? "" : "s"} today</strong></div></article>)}</div></section>
      <section className="section section-dark" id="research"><div><Badge tone="demo">Research contract</Badge><h2>Performance needs context.</h2><p>Research, validation, final out-of-sample and shadow results are kept separate. 2026 data cannot be used to choose parameters.</p><Link className="button button-light" to="/research">Open Research <ArrowRight size={17} /></Link></div><div className="periods"><div><span>Research</span><strong>2010–2024</strong></div><div><span>Validation</span><strong>2025</strong></div><div><span>Final out-of-sample</span><strong>2026 → current</strong></div><small>Demo metrics are explicitly labelled and are not claims of performance.</small></div></section>
      <section className="section recent" id="about"><SectionHeading eyebrow="Latest from the engine" title="Recent analyses" action={<Link className="text-link" to="/scanner">View scanner <ArrowRight size={16} /></Link>} /><div className="analysis-grid">{demoData.candidates.slice(0, 3).map((c) => <Link to={`/stocks/${c.symbol}`} className="analysis-card" key={c.symbol}><div><span className="ticker-icon">{c.symbol.slice(0, 1)}</span><span><strong>{c.symbol}</strong><small>{c.company}</small></span><SignalBadge status={c.status} /></div><div><span>Quant score</span><strong>{c.quantScore}<small>/100</small></strong></div><div className="score-bar"><i style={{ width: `${c.quantScore}%` }} /></div><footer><span>{c.strategy}</span><ArrowRight size={16} /></footer></Link>)}</div></section>
    </main><PublicFooter />
  </div>;
}

export function DashboardPage() {
  const demoData = useData();
  const { status, scan, portfolio, candidates, strategies } = demoData;
  return <><PageTitle eyebrow="Public dashboard" title="Market overview" text="Latest engine state, decisions and simulated positions." /><div className="status-strip"><span className="online-dot" /><div><span className="eyebrow">ENGINE</span><strong>{status.engine.toUpperCase()}</strong></div><div><span>Latest scan</span><strong>{formatDate(status.latestScan)}</strong></div><div><span>Next scan</span><strong>{formatDate(status.nextScan)}</strong></div><Badge tone="demo">Demo Data</Badge></div><div className="metrics-grid"><MetricCard label="Universe" value={scan.universe.toLocaleString()} detail="Stocks scanned" /><MetricCard label="Passed filters" value={scan.passedFilters.toLocaleString()} detail="Core universe" /><MetricCard label="Candidates" value={scan.candidates} detail="For strategy review" /><MetricCard label="Strong setups" value={scan.setups} detail="Across active strategies" accent /></div><div className="dashboard-grid"><section className="panel panel-large"><SectionHeading title="Latest decisions" action={<Link to="/scanner">Full scanner</Link>} /><CandidateList candidates={candidates.slice(0, 4)} /></section><section className="panel"><SectionHeading title="Shadow portfolio" action={<Link to="/portfolio">Details</Link>} /><div className="portfolio-hero"><span>Simulated equity</span><strong>{formatMoney(portfolio.equity)}</strong><Badge tone="positive">+{portfolio.returnPct}%</Badge></div><div className="mini-stats"><span>Open positions<strong>{portfolio.openPositions}</strong></span><span>Open risk<strong>{portfolio.openRiskPct}%</strong></span><span>Initial capital<strong>{formatMoney(portfolio.initialCapital)}</strong></span></div></section><section className="panel panel-large"><SectionHeading title="Recent activity" action={<Link to="/activity">All activity</Link>} /><Timeline compact /></section><section className="panel"><SectionHeading title="Strategies running" /><div className="strategy-mini">{strategies.map((s) => <Link to={`/strategies/${s.id}`} key={s.id}><span><i className="online-dot" /><strong>{s.name}</strong><small>v{s.version} · {s.state}</small></span><span>{s.signalsToday} signals<ChevronRight size={15} /></span></Link>)}</div></section></div></>;
}

function PageTitle({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) { return <div className="page-title"><div><span className="eyebrow accent-text">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>; }

function CandidateList({ candidates }: { candidates: Candidate[] }) { return <div className="candidate-list">{candidates.map((c) => <Link to={`/stocks/${c.symbol}`} key={c.symbol}><span className="ticker-icon">{c.symbol[0]}</span><span><strong>{c.symbol}</strong><small>{c.company}</small></span><span className="candidate-strategy">{c.strategy}</span><span className="score"><strong>{c.quantScore}</strong>/100</span><SignalBadge status={c.status} /><ChevronRight size={16} /></Link>)}</div>; }

export function ScannerPage() {
  const demoData = useData();
  const [strategy, setStrategy] = useState("all"), [signal, setSignal] = useState("all"), [sector, setSector] = useState("all"), [minScore, setMinScore] = useState(0), [sort, setSort] = useState("score");
  const rows = useMemo(() => demoData.candidates.filter((c) => (strategy === "all" || c.strategyId === strategy) && (signal === "all" || c.status === signal) && (sector === "all" || c.sector === sector) && c.quantScore >= minScore).sort((a, b) => sort === "symbol" ? a.symbol.localeCompare(b.symbol) : b.quantScore - a.quantScore), [demoData.candidates, strategy, signal, sector, minScore, sort]);
  return <><PageTitle eyebrow="Latest scan" title="Market scanner" text="Explore model candidates and structured rejection reasons." action={<Badge tone="demo">Demo Data</Badge>} /><div className="filter-bar"><label><Filter size={15} /> Strategy<select value={strategy} onChange={(e) => setStrategy(e.target.value)}><option value="all">All</option>{demoData.strategies.map((s) => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Signal<select value={signal} onChange={(e) => setSignal(e.target.value)}><option value="all">All</option><option>Strong Setup</option><option>Watch</option><option>No Setup</option><option>Rejected</option></select></label><label>Sector<select value={sector} onChange={(e) => setSector(e.target.value)}><option value="all">All</option>{[...new Set(demoData.candidates.map((c) => c.sector))].map((s) => <option key={s}>{s}</option>)}</select></label><label>Min score<select value={minScore} onChange={(e) => setMinScore(Number(e.target.value))}><option value="0">Any</option><option value="60">60+</option><option value="75">75+</option><option value="85">85+</option></select></label><label>Sort<select value={sort} onChange={(e) => setSort(e.target.value)}><option value="score">Score</option><option value="symbol">Ticker</option></select></label></div><div className="table-card"><div className="responsive-table scanner-table"><div className="table-row table-head"><span>Stock</span><span>Price</span><span>Score</span><span>Strategy</span><span>Trend</span><span>Momentum</span><span>Rel. strength</span><span>Volume</span><span>Earnings</span><span>Status</span></div>{rows.map((c) => <Link to={`/stocks/${c.symbol}`} className="table-row" key={c.symbol}><span data-label="Stock"><strong>{c.symbol}</strong><small>{c.company}</small></span><span data-label="Price">{formatMoney(c.price)}</span><span data-label="Score"><strong>{c.quantScore}</strong>/100</span><span data-label="Strategy">{c.strategy}</span><span data-label="Trend">{c.trend}</span><span data-label="Momentum">{c.momentum}</span><span data-label="Rel. strength">{c.relativeStrength}</span><span data-label="Volume">{c.relativeVolume.toFixed(2)}x</span><span data-label="Earnings">{c.earningsDate ?? "—"}</span><span data-label="Status"><SignalBadge status={c.status} /></span></Link>)}</div>{rows.length === 0 && <div className="empty-state"><Search /><strong>No candidates match these filters</strong><button onClick={() => { setStrategy("all"); setSignal("all"); setSector("all"); setMinScore(0); }}>Clear filters</button></div>}</div><p className="table-note">Updated {formatDate(demoData.status.latestScan)} · US market times shown in ET.</p></>;
}

function PriceChart({ score }: { score: number }) { return <div className="chart-placeholder" role="img" aria-label="Prepared OHLCV chart placeholder"><div className="chart-grid" /><svg viewBox="0 0 800 240" preserveAspectRatio="none"><path d="M0 205 C60 190,90 210,140 174 S220 185,260 146 S340 168,390 124 S470 142,520 92 S600 110,650 68 S730 82,800 35" fill="none" stroke="currentColor" strokeWidth="3" vectorEffect="non-scaling-stroke" /><path d="M0 205 C60 190,90 210,140 174 S220 185,260 146 S340 168,390 124 S470 142,520 92 S600 110,650 68 S730 82,800 35 L800 240 L0 240Z" fill="url(#area)" opacity=".2" /><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#25745a" /><stop offset="1" stopColor="#25745a" stopOpacity="0" /></linearGradient></defs></svg><div className="chart-caption"><span>OHLCV adapter ready</span><strong>Quant score {score}/100</strong></div></div>; }

export function StockPage() {
  const demoData = useData();
  const { symbol = "NVDA" } = useParams(); const stock = demoData.candidates.find((c) => c.symbol === symbol.toUpperCase()) ?? demoData.candidates[0]!;
  return <><PageTitle eyebrow={`${stock.sector} · US Equity`} title={stock.symbol} text={stock.company} action={<div className="title-actions"><SignalBadge status={stock.status} /><Badge tone="neutral">Quant Signal · {stock.direction}</Badge></div>} /><div className="stock-hero"><div><span>Price overview</span><strong>{formatMoney(stock.price)}</strong><small>Demo snapshot · not live market data</small></div><div className="score-ring" style={{ "--score": `${stock.quantScore * 3.6}deg` } as React.CSSProperties}><span><strong>{stock.quantScore}</strong>/100</span></div></div><div className="factor-grid"><MetricCard label="Trend" value={stock.trend} detail="EMA structure" /><MetricCard label="Momentum" value={stock.momentum} detail="Composite score" /><MetricCard label="Relative strength" value={stock.relativeStrength} detail="vs SPY / QQQ" /><MetricCard label="Volume" value={`${stock.relativeVolume}x`} detail="vs ADV20" /><MetricCard label="Volatility" value="Medium" detail="ATR% regime" /></div><div className="stock-grid"><section className="panel panel-large"><SectionHeading title="Price structure" text="The chart component is prepared for real OHLCV data. Demo shape shown." /><PriceChart score={stock.quantScore} /></section><section className="panel"><SectionHeading title={stock.status === "Rejected" ? "Rejected because" : "Why this setup was selected"} text="Public, structured rationale — never private chain-of-thought." /><Rationale reasons={stock.reasons} /></section><section className="panel"><SectionHeading title="Strategy" /><Link className="strategy-link" to={`/strategies/${stock.strategyId}`}><Target /><span><strong>{stock.strategy} V1</strong><small>Version 1.0.0 · {stock.status}</small></span><ChevronRight /></Link><div className="detail-list"><span>Market structure<strong>{stock.trend}</strong></span><span>20D breakout<strong>{stock.quantScore > 80 ? "Confirmed" : "Not confirmed"}</strong></span><span>50D breakout<strong>{stock.quantScore > 85 ? "Confirmed" : "Pending"}</strong></span></div></section><section className="panel"><SectionHeading title="Earnings & events" /><div className="event-callout"><CalendarDays /><div><strong>{stock.earningsDate ?? "Date unavailable"}</strong><span>{stock.earningsProximityDays !== null && stock.earningsProximityDays > 0 ? `${stock.earningsProximityDays} days away` : "Recent event"}</span></div></div><p className="muted">Event analysis adapter is ready for a future earnings provider and structured AI assessment.</p></section><section className="panel panel-full"><SectionHeading title="Latest decisions" /><Timeline compact symbol={stock.symbol} /></section></div></>;
}

export function StrategiesPage() { const demoData = useData(); return <><PageTitle eyebrow="Strategy registry" title="Systematic strategies" text="Every strategy is versioned and exposed through shared metadata." /><div className="strategy-grid">{demoData.strategies.map((s) => <Link to={`/strategies/${s.id}`} className="strategy-card" key={s.id}><header><span className="icon-box"><Target /></span><Badge tone={s.state === "Shadow" ? "positive" : "neutral"}>{s.state}</Badge></header><span className="eyebrow">{s.id} · v{s.version}</span><h2>{s.name} V1</h2><p>{s.description}</p><div className="detail-list"><span>Universe<strong>{s.universe}</strong></span><span>Holding period<strong>{s.holdingPeriod}</strong></span><span>Signals today<strong>{s.signalsToday}</strong></span><span>Open positions<strong>{s.openPositions}</strong></span></div><footer>View strategy <ArrowRight /></footer></Link>)}</div><div className="info-callout"><Sparkles /><div><strong>Metadata-driven architecture</strong><p>A future <code>momentum_v1</code> strategy appears here automatically after registration through the API/database.</p></div></div></>;
}

export function StrategyPage() {
  const demoData = useData();
  const { strategyId } = useParams(); const strategy = demoData.strategies.find((s) => s.id === strategyId) ?? demoData.strategies[0]!; const candidates = demoData.candidates.filter((c) => c.strategyId === strategy.id);
  return <><PageTitle eyebrow={`${strategy.id} · v${strategy.version}`} title={`${strategy.name} V1`} text={strategy.description} action={<Badge tone={strategy.state === "Shadow" ? "positive" : "neutral"}>{strategy.state}</Badge>} /><div className="metrics-grid"><MetricCard label="Signals today" value={strategy.signalsToday} /><MetricCard label="Open positions" value={strategy.openPositions} /><MetricCard label="Universe" value="US Core" detail={strategy.universe} /><MetricCard label="Holding period" value={strategy.holdingPeriod} /></div><div className="dashboard-grid"><section className="panel panel-large"><SectionHeading title="Current candidates" /><CandidateList candidates={candidates} /></section><section className="panel"><SectionHeading title="Published configuration" text="Baseline parameters, not optimised claims." /><div className="detail-list">{Object.entries(strategy.parameters).map(([key, value]) => <span key={key}>{key}<strong>{String(value)}</strong></span>)}</div></section><section className="panel"><SectionHeading title="Lifecycle" /><div className="lifecycle"><span className="done">Research</span><span className={strategy.state !== "Research" ? "done" : ""}>Validation</span><span className={strategy.state === "Shadow" ? "active" : ""}>Shadow</span><span>Live</span></div></section><section className="panel panel-large"><SectionHeading title="Methodology" /><Rationale reasons={demoData.candidates.find((c) => c.strategyId === strategy.id)?.reasons ?? []} /><Link className="text-link" to="/methodology">Read complete methodology <ArrowRight /></Link></section></div></>;
}

const metricLabels: Record<string, string> = { cagr: "CAGR", totalReturn: "Total return", maxDrawdown: "Max drawdown", profitFactor: "Profit factor", expectancy: "Expectancy", sharpe: "Sharpe", sortino: "Sortino", calmar: "Calmar", trades: "Trades", winRate: "Win rate", averageWin: "Average win", averageLoss: "Average loss", exposure: "Exposure", averageHoldingPeriod: "Avg. holding period" };
export function ResearchPage() { const demoData = useData(); return <><PageTitle eyebrow="Evidence library" title="Research & backtests" text="Results remain separated by lifecycle stage and cost scenario." action={<Badge tone="demo">Demo metrics</Badge>} /><div className="research-warning"><FlaskConical /><p><strong>Research contract enforced.</strong> 2026 data is reserved for final out-of-sample evaluation and cannot select parameters.</p><Link to="/methodology">Read contract</Link></div><div className="research-table table-card"><div className="table-row table-head"><span>Strategy</span><span>Stage</span><span>Period</span><span>CAGR</span><span>Max drawdown</span><span>Sharpe</span><span>Trades</span><span>Status</span></div>{demoData.research.map((r) => <Link className="table-row" to={`/research/${r.id}`} key={r.id}><span data-label="Strategy"><strong>{r.strategy}</strong><small>NORMAL cost scenario</small></span><span data-label="Stage"><Badge>{r.stage}</Badge></span><span data-label="Period">{r.period}</span><span data-label="CAGR">{r.metrics.cagr}%</span><span data-label="Max drawdown">{r.metrics.maxDrawdown}%</span><span data-label="Sharpe">{r.metrics.sharpe}</span><span data-label="Trades">{r.metrics.trades}</span><span data-label="Status"><Badge tone="demo">{r.status}</Badge></span></Link>)}</div><div className="benchmark-panel"><SectionHeading title="Benchmark comparison prepared" text="Backtest contracts support Strategy, SPY and QQQ with LOW_COST, NORMAL and STRESS execution scenarios." /><div><span>Strategy</span><span>SPY</span><span>QQQ</span></div></div></>;
}

export function ResearchDetailPage() { const demoData = useData(); const { researchId } = useParams(); const result = demoData.research.find((r) => r.id === researchId) ?? demoData.research[0]!; return <><PageTitle eyebrow={`${result.stage} · ${result.period}`} title={result.strategy} text="Illustrative demo output until validated point-in-time market data is connected." action={<Badge tone="demo">Demo results</Badge>} /><div className="metric-detail-grid">{Object.entries(result.metrics).map(([key, value]) => <MetricCard key={key} label={metricLabels[key] ?? key} value={value === null ? "—" : `${value}${["cagr", "totalReturn", "maxDrawdown", "winRate", "averageWin", "averageLoss", "exposure"].includes(key) ? "%" : ""}`} />)}</div><section className="panel"><SectionHeading title="Validation boundaries" /><div className="period-timeline"><span className="active"><strong>Research</strong>2010–2024</span><span><strong>Validation</strong>2025</span><span><strong>Final OOS</strong>2026 → current</span><span><strong>Shadow</strong>Pending</span><span><strong>Live</strong>Not enabled</span></div></section></>;
}

export function PortfolioPage() { const demoData = useData(); const { portfolio, positions } = demoData; return <><PageTitle eyebrow="Simulated execution" title="Shadow Portfolio" text="Virtual positions only. No broker connection and no real capital." action={<Badge tone="warning">Simulated</Badge>} /><div className="portfolio-banner"><div><span>Shadow equity</span><strong>{formatMoney(portfolio.equity)}</strong><Badge tone="positive">+{portfolio.returnPct}%</Badge></div><div><span>Initial capital<strong>{formatMoney(portfolio.initialCapital)}</strong></span><span>Open positions<strong>{portfolio.openPositions} / 4</strong></span><span>Open risk<strong>{portfolio.openRiskPct}% / 2%</strong></span><span>Gross exposure<strong>21.4% / 100%</strong></span></div></div><section className="panel"><SectionHeading title="Open model positions" /><div className="responsive-table portfolio-table"><div className="table-row table-head"><span>Position</span><span>Strategy</span><span>Entry</span><span>Current</span><span>Stop</span><span>Qty</span><span>Risk</span><span>Unrealized P&L</span><span>R multiple</span></div>{positions.map((p) => <div className="table-row" key={p.symbol}><span data-label="Position"><strong>{p.symbol}</strong><small>Opened {formatDate(p.openedAt)}</small></span><span data-label="Strategy">{p.strategy}</span><span data-label="Entry">{formatMoney(p.entryPrice)}</span><span data-label="Current">{formatMoney(p.currentPrice)}</span><span data-label="Stop">{formatMoney(p.stopPrice)}</span><span data-label="Qty">{p.quantity}</span><span data-label="Risk">{formatMoney(p.riskAmount)}</span><span data-label="Unrealized P&L" className="positive-text">+{formatMoney(p.unrealizedPnl)}</span><span data-label="R multiple">+{p.rMultiple}R</span></div>)}</div></section><section className="panel"><SectionHeading title="Risk policy" text="Hard limits are deterministic and cannot be changed by AI." /><div className="risk-grid">{[["Risk / trade", "0.5%"], ["Max positions", "4"], ["Max open risk", "2%"], ["Max single position", "30%"], ["Max sector exposure", "40%"], ["Leverage", "None"], ["Averaging down", "Disabled"], ["Martingale", "Disabled"]].map(([a, b]) => <span key={a}>{a}<strong>{b}</strong></span>)}</div></section></>;
}

export function EarningsPage() { const demoData = useData(); return <><PageTitle eyebrow="Event calendar" title="Earnings" text="Upcoming and recent events affecting tracked stocks and strategies." /><div className="earnings-grid">{demoData.earnings.map((e) => <article className="earning-card" key={`${e.symbol}-${e.date}`}><header><span className="ticker-icon">{e.symbol[0]}</span><span><strong>{e.symbol}</strong><small>{e.company}</small></span><Badge tone={e.eventSignal === "Confirmed" ? "positive" : e.eventSignal === "Risk Window" ? "warning" : "neutral"}>{e.eventSignal}</Badge></header><div><CalendarDays /><span><small>{new Date(e.date) < new Date("2026-08-10") ? "Reported" : "Expected"}</small><strong>{e.date} · {e.timing}</strong></span></div><footer>{e.strategies.map((s) => <Badge key={s}>{s}</Badge>)}{e.tracked && <span><CircleDot /> Tracked</span>}</footer></article>)}</div><div className="info-callout"><Clock3 /><div><strong>Timing-aware by design</strong><p>BMO, AMC and exact availability timestamps will be stored when supplied by the future earnings provider.</p></div></div></>;
}

function Timeline({ compact = false, symbol }: { compact?: boolean; symbol?: string }) { const demoData = useData(); const events = demoData.events.filter((e) => !symbol || e.symbol === symbol || !e.symbol).slice(0, compact ? 5 : undefined); return <div className="timeline">{events.map((e) => <div key={e.id}><i className={`event-dot event-${e.severity}`} /><span><strong>{e.type.replaceAll("_", " ")}</strong><p>{e.message}</p><small>{formatDate(e.createdAt)}{e.symbol ? ` · ${e.symbol}` : ""}</small></span></div>)}</div>; }
export function ActivityPage() { const demoData = useData(); const [type, setType] = useState("all"); const events = type === "all" ? demoData.events : demoData.events.filter((e) => e.type.includes(type)); return <><PageTitle eyebrow="Audit timeline" title="Engine activity" text="Safe public events prepared for periodic polling or Server-Sent Events." /><div className="filter-bar"><label><SlidersHorizontal /> Event<select value={type} onChange={(e) => setType(e.target.value)}><option value="all">All events</option><option value="SCAN">Scans</option><option value="SIGNAL">Signals</option><option value="FILTER">Filters</option><option value="ERROR">Errors</option></select></label></div><section className="panel"><div className="timeline">{events.map((e) => <div key={e.id}><i className={`event-dot event-${e.severity}`} /><span><strong>{e.type.replaceAll("_", " ")}</strong><p>{e.message}</p><small>{formatDate(e.createdAt)}{e.symbol ? ` · ${e.symbol}` : ""}</small></span></div>)}</div></section></>;
}

export function StatusPage() { const demoData = useData(); const s = demoData.status; return <><PageTitle eyebrow="Safe public health" title="System status" text="Operational information without private infrastructure details." /><div className="system-ok"><Check /><div><strong>All public systems operational</strong><span>Demo state — live health will replace this after deployment.</span></div></div><section className="panel status-list">{[["Research engine", s.engine, "Latest successful scan " + formatDate(s.latestScan)], ["Public API", s.apiHealth, "Read-only endpoints responding"], ["Market data", "current", "Updated " + formatDate(s.lastDataUpdate)], ["Strategy registry", "operational", `${demoData.strategies.length} strategies active`], ["Shadow portfolio", "operational", `${demoData.positions.length} positions tracked`]].map(([name, state, detail]) => <div key={name}><span className="online-dot" /><span><strong>{name}</strong><small>{detail}</small></span><Badge tone="positive">{state}</Badge></div>)}</section><div className="security-note"><LockKeyhole /><div><strong>Private by design</strong><p>This page never exposes server IPs, ports, stack traces, internal paths, credentials or private provider status.</p></div></div></>;
}

function LegalLayout({ title, children }: { title: string; children: React.ReactNode }) { return <div className="legal-page"><header className="landing-nav"><Link to="/" className="brand"><span className="brand-mark"><BarChart3 size={19} /></span><span>Stock Autotrader</span></Link><Link className="button button-small" to="/dashboard">Dashboard</Link></header><main><span className="eyebrow accent-text">Stock Autotrader V5.1</span><h1>{title}</h1>{children}</main><PublicFooter /></div>; }
export function MethodologyPage() { return <LegalLayout title="Methodology"><p className="lead">Stock Autotrader is a systematic research platform. It filters a defined US equity universe, calculates deterministic features, applies versioned strategy rules and publishes structured outcomes.</p><h2>Signal language</h2><p><strong>Strong Setup</strong>, <strong>Watch</strong> and <strong>No Setup</strong> describe model outputs. Bullish, Neutral and Bearish are labelled Quant Signal or Model Signal. None is personalised advice.</p><h2>Decision rationale</h2><p>Public rationale contains observable inputs, thresholds and pass/reject codes. The system does not publish or store private model chain-of-thought.</p><h2>Research boundaries</h2><div className="legal-grid"><span><strong>Research</strong>2010-01-01 → 2024-12-31</span><span><strong>Validation</strong>2025-01-01 → 2025-12-31</span><span><strong>Final out-of-sample</strong>2026-01-01 → current</span></div><p>2026 cannot be used to choose parameters. Tests must address look-ahead bias, survivorship bias, point-in-time membership, corporate actions, slippage, commission, spreads, gap risk and information availability timestamps.</p><h2>Shadow mode</h2><p>The shadow portfolio uses virtual entries, stops and exits. It does not send orders, access a broker or use real capital.</p></LegalLayout>; }
export function DisclaimerPage() { return <LegalLayout title="Disclaimer"><p className="lead">Stock Autotrader provides general, model-generated research for educational and informational purposes only.</p><h2>Not investment advice</h2><p>Nothing on this website is a recommendation, offer, solicitation or personalised assessment to buy, hold or sell a security. Signals may be incomplete, delayed, wrong or unsuitable for you.</p><h2>Simulated performance</h2><p>Shadow portfolios and demo/backtest results are hypothetical. They do not represent actual trading, do not include every real-world constraint and must not be presented as guaranteed returns.</p><h2>Risk</h2><p>Equities and swing trading involve risk, including loss of capital, gaps through stops, liquidity changes and data errors. Past or simulated performance does not guarantee future results.</p><h2>No guarantees</h2><p>The service is provided without a guarantee of availability, accuracy, completeness or outcome. Verify information independently and seek regulated professional advice when needed.</p></LegalLayout>; }
export function NotFoundPage() { return <div className="not-found"><Gauge /><h1>Page not found</h1><p>The requested public view does not exist.</p><Link className="button" to="/dashboard">Open dashboard</Link></div>; }
