// @ts-nocheck -- stage tuples are runtime-guarded by the intersection observer.
import { FormEvent, useEffect, useRef, useState } from "react";
import { Activity, ArrowUpRight, FileText, Search, Scale, ShieldAlert, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { motion } from "motion/react";
import { Link } from "react-router-dom";
import { Shell } from "../components/layout/Shell";
import { Atmosphere } from "../components/visual/Atmosphere";
import { SponsorRail } from "../components/sponsors/SponsorRail";

const stages = [
  ["Frame the question", "Start with a ticker.", "Choose a company. One symbol becomes a research brief.", Search],
  ["Market context", "Read the world around it.", "Market and Fundamentals Analysts gather context before opinions form.", Activity],
  ["Bull Researcher", "Build the strongest upside case.", "Bull Researcher argues what could go right — using evidence, not enthusiasm.", TrendingUp],
  ["Bear Researcher", "Stress-test the story.", "Bear Researcher looks for what the first answer missed.", ShieldAlert],
  ["Risk review", "Put disagreement to work.", "Risk weighs both sides before a conclusion is written.", Scale],
  ["Portfolio Manager", "Leave with a clear brief.", "One structured report you can read, question and use in your process.", FileText],
] as const;

export function LandingPage() {
  const [symbol, setSymbol] = useState(""); const [message, setMessage] = useState(""); const [active, setActive] = useState(0); const refs = useRef<(HTMLElement | null)[]>([]); const current = stages[active] ?? stages[0]!;
  useEffect(() => { const io = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && setActive(Number((e.target as HTMLElement).dataset.stage))), { rootMargin: "-38% 0px -45% 0px" }); refs.current.forEach(x => x && io.observe(x)); return () => io.disconnect(); }, []);
  const submit = (e: FormEvent) => { e.preventDefault(); setMessage("Backend connection not configured yet."); };
  return <Shell><SponsorRail/><main className="landing">
    <section className="hero-section"><Atmosphere/><div className="hero-inner"><motion.p className="eyebrow" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>Multi-agent investment research</motion.p><motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0, transition: { delay: .12 } }}>Understand the company<br/><em>before the noise.</em></motion.h1><motion.p className="hero-sub" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0, transition: { delay: .2 } }}>Enter a ticker and get a structured first read built from market context, fundamentals, news, opposing research and risk review.</motion.p><motion.form className="ticker-form" onSubmit={submit} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0, transition: { delay: .3 } }}><div className="ticker-input"><Search size={18}/><input value={symbol} onChange={e => setSymbol(e.target.value.toUpperCase())} placeholder="Enter a ticker, e.g. NVDA" maxLength={8} aria-label="Stock ticker"/><span>US</span></div><button className="primary-button" type="submit">Start a research brief <ArrowUpRight size={17}/></button></motion.form>{message && <p className="form-message" role="status" aria-live="polite">{message}</p>}<div className="popular" aria-label="Popular tickers"><span>Popular</span>{["NVDA","AAPL","MSFT","AMZN","GOOGL"].map(x => <button key={x} onClick={() => setSymbol(x)}>{x}</button>)}</div><p className="hero-disclaimer">A starting point for your own research — not financial advice.</p></div><div className="hero-scroll-cue">Scroll to see the research unfold <span>↓</span></div></section>
    <section className="proof-rail"><div><b>7</b><span>research roles</span></div><div><b>Bull ↔ Bear</b><span>opposing views</span></div><div><b>One report</b><span>structured synthesis</span></div></section>
    <section className="film-section" id="how-it-works"><div className="film-intro"><div className="section-kicker">01 / The process</div><h2>This is what happens<br/><em>after you enter a ticker.</em></h2><p>Scroll through the research room. Every stage adds context, tension or clarity to the final view.</p></div><div className="film-stage"><div className={`film-visual film-stage-${active}`}><div className="film-orbit orbit-a"/><div className="film-orbit orbit-b"/><div className={`film-signal stage-${active}`}><Sparkles size={15}/><span>LIVE RESEARCH</span></div><div className="film-evidence evidence-a"><span>MARKET CONTEXT</span><b>Signals, not noise</b><small>06 sources indexed</small></div><div className="film-evidence evidence-b"><span>FUNDAMENTALS</span><b>Revenue / margins</b><small>Evidence attached</small></div><div className="film-debate-chip chip-bull"><TrendingUp size={13}/> BULL CASE</div><div className="film-debate-chip chip-bear"><ShieldAlert size={13}/> BEAR CASE</div><div className="film-brief"><div><span>RESEARCH BRIEF</span><b>NVDA</b></div><i>READY FOR REVIEW</i><hr/><small>Executive summary</small><p>Context, opposing views and risk in one considered brief.</p></div><svg className="film-paths" viewBox="0 0 500 500" aria-hidden="true"><path d="M50 380 C150 40 350 40 450 380"/><path d="M80 415 C190 170 310 170 420 415"/><path className="film-path-active" d="M50 380 C150 40 350 40 450 380"/></svg><div className="film-active-node"><span>{String(active + 1).padStart(2, "0")}</span>{(() => { const I = stages[active][3]; return <I size={22}/>; })()}<small>{stages[active][0]}</small></div></div><div className="film-steps">{stages.map((s, i) => { const I = s[3]; return <article key={s[0]} ref={el => { refs.current[i] = el; }} data-stage={i} className={`film-step ${active === i ? "is-active" : ""}`}><span className="film-index">{String(i + 1).padStart(2, "0")}</span><div><div className="section-kicker">{String(i + 1).padStart(2, "0")} / {s[0]}</div><h3>{s[1]}</h3><p>{s[2]}</p></div><I size={19}/></article>; })}</div></div></section>
    <section className="bull-bear-film" id="agents"><div className="section-kicker">02 / The conversation</div><div className="debate-heading"><h2>Conviction is<br/><em>a conversation.</em></h2><p>Two researchers take the same evidence in opposite directions. That friction is where weak assumptions surface.</p></div><div className="argument-track"><article className="argument-card bull-card"><span>01 / Bull Researcher</span><h3>What could go right?</h3><p>Growth, catalysts and the evidence that supports the upside case.</p><div className="argument-line"><TrendingUp size={18}/></div></article><div className="argument-center"><div className="center-ring"><ShieldCheck size={18}/><span>Risk<br/>review</span></div><svg viewBox="0 0 260 120" aria-hidden="true"><path d="M0 20 C80 20 90 100 130 60 S190 20 260 100"/><path d="M0 100 C70 100 100 20 130 60 S190 100 260 20"/></svg></div><article className="argument-card bear-card"><span>02 / Bear Researcher</span><h3>What are we missing?</h3><p>Fragility, counter-evidence and the risks that can change the view.</p><div className="argument-line"><ShieldAlert size={18}/></div></article></div></section>
    <section className="use-case-section"><div className="section-kicker">03 / In practice</div><h2>A faster first read<br/><em>before the noise.</em></h2><div className="use-case-grid"><div className="use-case-visual"><div className="ticker-chip">NVDA <span>RESEARCH BRIEF</span></div><div className="scan-line"/><div className="use-case-note note-a">Read the context</div><div className="use-case-note note-b">Challenge the thesis</div><div className="use-case-note note-c">Keep risks visible</div></div><div className="use-case-copy"><p>Use it before earnings, before a portfolio review, or whenever a company deserves a closer look.</p><p>AI Analysis gives you a considered starting point — not a black-box answer. Follow the evidence, then make the call yourself.</p><Link to="/app" className="text-link">See the workspace <ArrowUpRight size={16}/></Link></div></div></section>
    <section className="report-section" id="reports"><div className="section-kicker">04 / Example output</div><div className="report-window"><div className="report-top"><span>ILLUSTRATIVE REPORT</span><span>AI ANALYSIS / 01</span></div><div className="report-grid"><div><p className="report-label">Executive summary</p><h2>Evidence first.<br/><em>Noise second.</em></h2><p className="report-text">A structured view of the company, the thesis behind it and the risks that could change the picture.</p></div><div className="report-outline"><span>01&nbsp;&nbsp; Investment thesis</span><span>02&nbsp;&nbsp; Bull case</span><span>03&nbsp;&nbsp; Bear case</span><span>04&nbsp;&nbsp; Fundamentals</span><span>05&nbsp;&nbsp; Risk review</span><span>06&nbsp;&nbsp; Final view</span></div></div></div></section>
    <section className="pricing-section" id="pricing"><div className="section-kicker">05 / Credits</div><h2>Keep research<br/><em>on your terms.</em></h2><p className="pricing-lede">Choose the way that fits your workflow. No subscription decisions today — just credits when you need a considered first read.</p><div className="credit-packs"><article><span>Invite a friend</span><b>Earn 1 analysis</b><p>Share your invite. When they register and complete their first analysis, one analysis comes back to you.</p><Link className="text-link" to="/account">Invite a friend <ArrowUpRight size={16}/></Link></article><article><span>5 credits</span><b>Price coming soon</b><p>A focused pack for the next few companies on your list.</p><button className="outline-button" onClick={() => setMessage("Credit checkout will connect to Stripe soon.")}>Choose 5 credits <ArrowUpRight size={16}/></button></article><article><span>10 credits</span><b>Price coming soon</b><p>More room for a steady research habit.</p><button className="outline-button" onClick={() => setMessage("Credit checkout will connect to Stripe soon.")}>Choose 10 credits <ArrowUpRight size={16}/></button></article></div>{message && <p className="form-message pricing-message" role="status">{message}</p>}</section><section className="final-cta"><div className="final-art"/><div className="section-kicker">Start with a question</div><h2>Choose the company.<br/><em>We’ll map the story.</em></h2><Link className="primary-button" to="/auth">Open your workspace <ArrowUpRight size={17}/></Link></section>
  </main></Shell>;
}
