const routes = [
  ["/api/status", "Safe public engine and API health", "Status"],
  ["/api/dashboard", "Aggregated dashboard snapshot", "Dashboard"],
  ["/api/scans/latest", "Latest scan summary", "Scan"],
  ["/api/scans/{id}", "Scan detail", "Scan"],
  ["/api/candidates", "Latest candidates", "CandidateList"],
  ["/api/stocks/{symbol}", "Public stock snapshot", "Candidate"],
  ["/api/stocks/{symbol}/analysis", "Structured stock analysis", "Analysis"],
  ["/api/strategies", "Strategy registry", "StrategyList"],
  ["/api/strategies/{id}", "Strategy metadata", "Strategy"],
  ["/api/research", "Research results", "ResearchList"],
  ["/api/backtests", "Backtest results", "ResearchList"],
  ["/api/portfolio/shadow", "Simulated portfolio", "Portfolio"],
  ["/api/trades/shadow", "Simulated trades", "TradeList"],
  ["/api/earnings", "Tracked earnings events", "EarningsList"],
  ["/api/activity", "Public engine events", "EventList"],
] as const;

const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const arrayOf = (name: string) => ({ type: "array", items: ref(name) });

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Stock Autotrader Public API",
    version: "5.1.0",
    description:
      "Read-only public observability API. No trading or administration endpoints.",
  },
  servers: [{ url: "/", description: "Current Worker" }],
  paths: Object.fromEntries(
    routes.map(([path, summary, schemaName]) => {
      const parameter = path.includes("{symbol}")
        ? {
            name: "symbol",
            in: "path",
            required: true,
            schema: { type: "string", pattern: "^[A-Z][A-Z0-9.-]{0,9}$" },
          }
        : path.includes("{id}")
          ? {
              name: "id",
              in: "path",
              required: true,
              schema: { type: "string", pattern: "^[a-zA-Z0-9_-]{1,80}$" },
            }
          : undefined;
      return [
        path,
        {
          get: {
            summary,
            ...(parameter ? { parameters: [parameter] } : {}),
            responses: {
              "200": {
                description: "Successful read",
                content: { "application/json": { schema: ref(schemaName) } },
              },
              "400": { $ref: "#/components/responses/InvalidInput" },
              "404": { $ref: "#/components/responses/NotFound" },
              "503": { $ref: "#/components/responses/Unavailable" },
            },
          },
        },
      ];
    }),
  ),
  components: {
    schemas: {
      Error: {
        type: "object",
        required: ["error"],
        properties: {
          error: {
            type: "object",
            required: ["code", "message"],
            properties: {
              code: { type: "string" },
              message: { type: "string" },
            },
          },
        },
      },
      DecisionReason: {
        type: "object",
        required: ["id", "outcome", "code", "label"],
        properties: {
          id: { type: "string" },
          outcome: { enum: ["pass", "reject", "info"] },
          code: { type: "string" },
          label: { type: "string" },
          observed: { type: "string" },
          threshold: { type: "string" },
        },
      },
      Status: {
        type: "object",
        required: [
          "engine",
          "latestScan",
          "nextScan",
          "lastDataUpdate",
          "apiHealth",
        ],
        properties: {
          engine: { enum: ["online", "offline", "delayed"] },
          latestScan: { type: ["string", "null"] },
          nextScan: { type: ["string", "null"] },
          lastDataUpdate: { type: ["string", "null"] },
          apiHealth: { enum: ["healthy", "degraded"] },
        },
      },
      Candidate: {
        type: "object",
        required: [
          "symbol",
          "company",
          "sector",
          "marketCap",
          "price",
          "quantScore",
          "strategyId",
          "strategyVersion",
          "strategy",
          "trend",
          "momentum",
          "relativeStrength",
          "relativeVolume",
          "earningsDate",
          "earningsProximityDays",
          "status",
          "direction",
          "updatedAt",
          "reasons",
        ],
        properties: {
          symbol: { type: "string" },
          company: { type: "string" },
          sector: { type: "string" },
          marketCap: { type: "number" },
          price: { type: "number" },
          quantScore: { type: "number", minimum: 0, maximum: 100 },
          strategyId: { type: "string" },
          strategyVersion: { type: "string" },
          strategy: { type: "string" },
          trend: { type: "string" },
          momentum: { type: "number" },
          relativeStrength: { type: "number" },
          relativeVolume: { type: "number" },
          earningsDate: { type: ["string", "null"] },
          earningsProximityDays: { type: ["number", "null"] },
          status: { enum: ["Strong Setup", "Watch", "No Setup", "Rejected"] },
          direction: { enum: ["Bullish", "Neutral", "Bearish"] },
          updatedAt: { type: "string" },
          reasons: arrayOf("DecisionReason"),
        },
      },
      CandidateList: arrayOf("Candidate"),
      Strategy: {
        type: "object",
        required: [
          "id",
          "name",
          "version",
          "description",
          "state",
          "enabled",
          "universe",
          "holdingPeriod",
          "signalsToday",
          "openPositions",
          "parameters",
        ],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          version: { type: "string" },
          description: { type: "string" },
          state: {
            enum: ["Research", "Validation", "Out-of-Sample", "Shadow", "Live"],
          },
          enabled: { type: "boolean" },
          universe: { type: "string" },
          holdingPeriod: { type: "string" },
          signalsToday: { type: "integer" },
          openPositions: { type: "integer" },
          parameters: { type: "object", additionalProperties: true },
        },
      },
      StrategyList: arrayOf("Strategy"),
      Research: {
        type: "object",
        required: [
          "id",
          "strategyId",
          "strategy",
          "stage",
          "period",
          "status",
          "metrics",
        ],
        properties: {
          id: { type: "string" },
          strategyId: { type: "string" },
          strategy: { type: "string" },
          stage: {
            enum: ["Research", "Validation", "Out-of-Sample", "Shadow", "Live"],
          },
          period: { type: "string" },
          status: { enum: ["Demo", "Pending", "Complete"] },
          metrics: {
            type: "object",
            additionalProperties: { type: ["number", "null"] },
          },
        },
      },
      ResearchList: arrayOf("Research"),
      Earnings: {
        type: "object",
        required: [
          "symbol",
          "company",
          "date",
          "timing",
          "eventSignal",
          "strategies",
          "tracked",
        ],
        properties: {
          symbol: { type: "string" },
          company: { type: "string" },
          date: { type: "string" },
          timing: { enum: ["BMO", "AMC", "TBD"] },
          eventSignal: { enum: ["Confirmed", "Pending", "Risk Window"] },
          strategies: { type: "array", items: { type: "string" } },
          tracked: { type: "boolean" },
        },
      },
      EarningsList: arrayOf("Earnings"),
      BotEvent: {
        type: "object",
        required: ["id", "type", "message", "severity", "createdAt"],
        properties: {
          id: { type: "string" },
          type: { type: "string" },
          message: { type: "string" },
          severity: { enum: ["info", "success", "warning", "error"] },
          symbol: { type: "string" },
          strategyId: { type: "string" },
          createdAt: { type: "string" },
        },
      },
      EventList: arrayOf("BotEvent"),
      Analysis: {
        type: "object",
        required: [
          "id",
          "symbol",
          "strategyId",
          "strategyVersion",
          "quantFactors",
          "marketStructure",
          "publicSummary",
          "aiAssessment",
          "dataSource",
          "dataAsOf",
          "createdAt",
          "updatedAt",
          "reasons",
        ],
        properties: {
          id: { type: "string" },
          symbol: { type: "string" },
          strategyId: { type: ["string", "null"] },
          strategyVersion: { type: ["string", "null"] },
          quantFactors: { type: "object" },
          marketStructure: { type: "object" },
          publicSummary: { type: "string" },
          aiAssessment: { type: ["object", "null"] },
          dataSource: { type: "string" },
          dataAsOf: { type: "string" },
          createdAt: { type: "string" },
          updatedAt: { type: "string" },
          reasons: arrayOf("DecisionReason"),
        },
      },
      Scan: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "scanType",
          "status",
          "universe",
          "passedFilters",
          "candidates",
          "setups",
          "dataSource",
          "dataAsOf",
          "startedAt",
          "completedAt",
          "demo",
        ],
        properties: {
          id: { type: "string" },
          scanType: { enum: ["PRE_MARKET", "POST_CLOSE", "MANUAL", "SMOKE"] },
          status: { enum: ["STARTED", "COMPLETED", "FAILED"] },
          universe: { type: "integer" },
          passedFilters: { type: "integer" },
          candidates: { type: "integer" },
          setups: { type: "integer" },
          dataSource: { type: "string" },
          dataAsOf: { type: "string" },
          startedAt: { type: "string" },
          completedAt: { type: ["string", "null"] },
          demo: { type: "boolean" },
        },
      },
      ScanSummary: {
        type: "object",
        required: ["universe", "passedFilters", "candidates", "setups"],
        properties: {
          universe: { type: "integer" },
          passedFilters: { type: "integer" },
          candidates: { type: "integer" },
          setups: { type: "integer" },
        },
      },
      Position: {
        type: "object",
        required: [
          "symbol",
          "strategy",
          "entryPrice",
          "currentPrice",
          "stopPrice",
          "quantity",
          "riskAmount",
          "unrealizedPnl",
          "rMultiple",
          "openedAt",
        ],
        properties: {
          symbol: { type: "string" },
          strategy: { type: "string" },
          entryPrice: { type: "number" },
          currentPrice: { type: "number" },
          stopPrice: { type: "number" },
          quantity: { type: "integer" },
          riskAmount: { type: "number" },
          unrealizedPnl: { type: "number" },
          rMultiple: { type: "number" },
          openedAt: { type: "string" },
        },
      },
      PortfolioSummary: {
        type: "object",
        required: [
          "initialCapital",
          "equity",
          "returnPct",
          "openPositions",
          "openRiskPct",
          "grossExposurePct",
          "maxPositions",
          "maxOpenRiskPct",
          "maxGrossExposurePct",
        ],
        properties: {
          initialCapital: { type: "number" },
          equity: { type: "number" },
          returnPct: { type: "number" },
          openPositions: { type: "integer" },
          openRiskPct: { type: "number" },
          grossExposurePct: { type: "number" },
          maxPositions: { type: "integer" },
          maxOpenRiskPct: { type: "number" },
          maxGrossExposurePct: { type: "number" },
        },
      },
      Portfolio: {
        allOf: [
          ref("PortfolioSummary"),
          {
            type: "object",
            required: ["simulated", "positions"],
            properties: {
              simulated: { type: "boolean" },
              positions: arrayOf("Position"),
            },
          },
        ],
      },
      TradeList: {
        type: "object",
        required: ["simulated", "trades"],
        properties: {
          simulated: { type: "boolean" },
          trades: { type: "array", items: { type: "object" } },
        },
      },
      Dashboard: {
        type: "object",
        required: [
          "demo",
          "status",
          "scan",
          "portfolio",
          "strategies",
          "candidates",
          "events",
          "earnings",
          "positions",
          "research",
        ],
        properties: {
          demo: { type: "boolean" },
          status: ref("Status"),
          scan: ref("ScanSummary"),
          portfolio: ref("PortfolioSummary"),
          strategies: ref("StrategyList"),
          candidates: ref("CandidateList"),
          events: ref("EventList"),
          earnings: ref("EarningsList"),
          positions: arrayOf("Position"),
          research: ref("ResearchList"),
        },
      },
    },
    responses: {
      InvalidInput: {
        description: "Invalid public identifier",
        content: { "application/json": { schema: ref("Error") } },
      },
      NotFound: {
        description: "Public resource not found",
        content: { "application/json": { schema: ref("Error") } },
      },
      Unavailable: {
        description: "Public data unavailable",
        content: { "application/json": { schema: ref("Error") } },
      },
    },
    securitySchemes: {},
  },
} as const;
